### ISSUE TITLE
Compiler error for ESP8266

### ISSUE THREAD

**Issue by Wijnand61** [olegv142/CC1101#1]
Oleg
This is my first contribution on GitHub. All 4 reasons for a simple library are top. But i want your library for LOLIN ESP8266 MCU's and get a compilation error for the examples, referring to the CC1101.cpp :99:67 error section attribute not allowed for 'data'
and that is the next line of code:
static void write_burst_pgm(uint8_t addr, uint8_t const * PROGMEM data, uint8_t len)
So PROGMEM is the issue, when i remove it, the compiler error disappears, but is that allowed?
static void write_burst_pgm(uint8_t addr, uint8_t const * data, uint8_t len)
The result of this is, that i can now upload it and start testing.
Wijnand

**Comment by olegv142** [comment]
Hello!
Yes the PROGMEM is the attribute of the Harward architecture of AVR, you
can safely ignore it or just #define PROGMEM
replacing it with nothing,
Regards,
 Oleg.

вс, 25 нояб. 2018 г. в 22:17, Wijnand61 <notifications@github.com>:

**Comment by Wijnand61** [comment]
Thanks Oleg
The free use of frequency band for 433 MHz in Netherlands is from 433.050 - 434.790, so i have to generate a different parameter table.
Regards
Wijnand
